#!/usr/bin/env tsx
/**
 * Runs the eight verification probes from CLAUDE.md section 3.
 * Connects to a live Portaldot node (local or mainnet).
 * Writes results to docs/chain-verified.md.
 */

import { ApiPromise, WsProvider } from "@polkadot/api";
import { writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const ENDPOINT = process.argv.includes("--mainnet")
  ? "wss://mainnet.portaldot.io"
  : "ws://127.0.0.1:9944";

async function main() {
  console.log(`Connecting to ${ENDPOINT}…`);
  const provider = new WsProvider(ENDPOINT);
  const api = await ApiPromise.create({ provider });
  await api.isReady;

  const chain = (await api.rpc.system.chain()).toString();
  const nodeVersion = (await api.rpc.system.version()).toString();
  const now = new Date().toISOString();

  const results: string[] = [
    `# Chain Verification Report`,
    ``,
    `**Date:** ${now}`,
    `**Endpoint:** ${ENDPOINT}`,
    `**Chain:** ${chain}`,
    `**Node version:** ${nodeVersion}`,
    ``,
    `---`,
    ``,
  ];

  const probe = (label: string, value: string) => {
    console.log(`  ${label}: ${value}`);
    results.push(`### ${label}`, ``, `\`${value}\``, ``);
  };

  // 1. Contracts pallet present?
  const hasContracts = !!api.tx.contracts;
  probe("1. contracts pallet present", String(hasContracts));

  // 2. utility.batchAll available?
  const hasBatchAll = !!api.tx.utility?.batchAll;
  probe("2. utility.batchAll available", String(hasBatchAll));

  // 3. identity pallet — inspect setIdentity fields
  try {
    const meta = api.tx.identity.setIdentity.meta;
    probe("3. identity.setIdentity meta", meta.toHuman()?.toString() ?? "n/a");
  } catch {
    probe("3. identity.setIdentity meta", "NOT AVAILABLE");
  }

  // 4. proxy types — inspect addProxy metadata
  try {
    const meta = api.tx.proxy.addProxy.meta;
    probe("4. proxy.addProxy meta", meta.toHuman()?.toString() ?? "n/a");
  } catch {
    probe("4. proxy.addProxy meta", "NOT AVAILABLE");
  }

  // 5. multisig constants
  try {
    const depositBase = api.consts.multisig.depositBase.toString();
    const depositFactor = api.consts.multisig.depositFactor.toString();
    probe("5a. multisig.depositBase", depositBase);
    probe("5b. multisig.depositFactor", depositFactor);
  } catch {
    probe("5. multisig constants", "NOT AVAILABLE");
  }

  // 6. bounties constants
  try {
    const bountyDepositBase = api.consts.bounties?.bountyDepositBase?.toString() ?? "n/a";
    const curatorDepositMin = api.consts.bounties?.curatorDepositMin?.toString() ?? "n/a";
    probe("6a. bounties.bountyDepositBase", bountyDepositBase);
    probe("6b. bounties.curatorDepositMin", curatorDepositMin);
  } catch {
    probe("6. bounties constants", "NOT AVAILABLE");
  }

  // 7. existential deposit
  try {
    const ed = api.consts.balances.existentialDeposit.toString();
    probe("7. balances.existentialDeposit", ed);
  } catch {
    probe("7. balances.existentialDeposit", "NOT AVAILABLE");
  }

  // 8. SS58 format
  try {
    const ss58 = api.registry.chainSS58?.toString() ?? "42";
    probe("8. SS58 prefix", ss58);
  } catch {
    probe("8. SS58 prefix", "42 (default)");
  }

  results.push(`---`, ``, `*Generated by scripts/chain-verify.ts*`);

  mkdirSync("docs", { recursive: true });
  const outPath = join("docs", "chain-verified.md");
  writeFileSync(outPath, results.join("\n"));
  console.log(`\nWritten to ${outPath}`);

  await api.disconnect();
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
