// Auto-generated by scripts/deploy.ts at 2026-05-30T19:47:16.729Z
import type { ContractAddresses } from "../types.js";

export const LOCAL_ADDRESSES: ContractAddresses = {
  "registry": "5CPvTCXFrpBnKDpymdYjfvHmKTnaijVTR7LViAxMnaELg9DY",
  "resolver": "5GydgnN1JAdFCKS1rq89cSdCxPQMCoJLMasxMiqMQ7zB5ZMB",
  "reverseRegistrar": "5HhMCMVwASenyzXuLpGrfLsMb3123QW8dT8JVxeHfxUnKQK2",
  "registrar": "5C8hGdU87FcH1y8xECiFGzzn14a6rupmCcLeeUsVffpuqKx8",
  "attestation": "5CKzLxL3S4HVyp2BJ8K8Rjvp9xFBhHGNQra9BsKor2CiUTpn"
};
