// Auto-generated by scripts/deploy.ts at 2026-05-30T19:30:42.976Z
import type { ContractAddresses } from "../types.js";

export const LOCAL_ADDRESSES: ContractAddresses = {
  "registry": "5Crn2ZTmzVN1JYT6ammNHKVvU4xGYB1bqeuDC18Em2crfKcN",
  "resolver": "5FSc7mD2R7BUJchFmUwvECgrQNkbn1EyZ4jridS9x8B2o3i1",
  "reverseRegistrar": "5GkGYbKmyzCUueBT5HLsYttSGemLz5Nbuw1h7PRzuMrXfw7r",
  "registrar": "5CFSHGxqhHzXPKsxDDzaCbopMtgEFk436j8wKRPHeqB9NtpP",
  "attestation": "5CqUdU9Jh7bGN9DXfw6dBC689GsmxjHoRGcySz4kBsBjVHpk"
};
